api/src/Entity/Address.php
<?php
/*
 * Copyright 2021,2022 Maxime Girardet
 *
 * This file is part of Nova.
 *
 * Nova is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Nova is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Nova. If not, see <https://www.gnu.org/licenses/agpl-3.0.html>.
 */

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ApiResource(normalizationContext: ['groups' => ['worksite']])]
#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column(type: 'integer')]
	private $id;

	#[Groups(['worksite', 'worksite_summary'])]
	#[ORM\Column(type: 'string', length: 255)]
	private $street;

	#[Groups(['worksite', 'worksite_summary'])]
	#[ORM\Column(type: 'integer')]
	private $postal_code;

	#[Groups(['worksite', 'worksite_summary'])]
	#[ORM\Column(type: 'string', length: 255)]
	private $city;

	#[ORM\OneToMany(mappedBy: 'address', targetEntity: Worksite::class)]
	private $worksites;

	public function __construct()
	{
		$this->worksites = new ArrayCollection();
	}

	public function getId(): ?int
	{
		return $this->id;
	}

	public function getStreet(): ?string
	{
		return $this->street;
	}

	public function setStreet(string $street): self
	{
		$this->street = $street;

		return $this;
	}

	public function getPostalCode(): ?int
	{
		return $this->postal_code;
	}

	public function setPostalCode(int $postal_code): self
	{
		$this->postal_code = $postal_code;

		return $this;
	}

	public function getCity(): ?string
	{
		return $this->city;
	}

	public function setCity(string $city): self
	{
		$this->city = $city;

		return $this;
	}

	/**
	 * @return Collection|Worksite[]
	 */
	public function getWorksites(): Collection
	{
		return $this->worksites;
	}

	public function addWorksite(Worksite $worksite): self
	{
		if (!$this->worksites->contains($worksite)) {
			$this->worksites[] = $worksite;
			$worksite->setAddress($this);
		}

		return $this;
	}

	public function removeWorksite(Worksite $worksite): self
	{
		if ($this->worksites->removeElement($worksite)) {
			// set the owning side to null (unless already changed)
			if ($worksite->getAddress() === $this) {
				$worksite->setAddress(null);
			}
		}

		return $this;
	}
}

api/src/Entity/VisitType.php
<?php
/*
 * Copyright 2021,2022 Maxime Girardet
 *
 * This file is part of Nova.
 *
 * Nova is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Nova is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Nova. If not, see <https://www.gnu.org/licenses/agpl-3.0.html>.
 */

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use App\Filter\VisitTypeFilter;
use App\Repository\VisitTypeRepository;
use App\State\VisitTypeProvider;
use DateInterval;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: VisitTypeRepository::class)]
#[ApiResource(
		normalizationContext: ['groups' => ['worksite', 'visit_type']],
		security: 'is_granted("ROLE_USER")',
		provider: VisitTypeProvider::class
)]
#[ApiFilter(SearchFilter::class, properties: ['worksite_status.short_name' => 'exact'])]
#[ApiFilter(BooleanFilter::class, properties: ['is_allowed_from_installation_only'])]
#[ApiFilter(VisitTypeFilter::class)]
class VisitType
{
	#[Groups(['worksite', 'worksite_summary', 'visit_type'])]
	#[ORM\ManyToMany(targetEntity: VisitStepType::class)]
	public $steps;

	#[Groups(['worksite', 'worksite_summary', 'visit_type'])]
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column(type: 'integer')]
	private $id;
	#[ORM\OneToMany(mappedBy: 'next_visit_type', targetEntity: Worksite::class)]
	private $worksites;

	#[ORM\OneToMany(mappedBy: 'type', targetEntity: Visit::class)]
	private $visits;

	#[Groups(['worksite', 'worksite_summary', 'visit_type'])]
	#[ORM\Column(type: 'string', length: 255)]
	private $short_name;

	#[Groups(['worksite', 'worksite_summary', 'visit_type'])]
	#[ORM\Column(type: 'string', length: 255)]
	private $long_name;

	#[Groups(['visit_type'])]
	#[ORM\Column(type: 'dateinterval', nullable: true)]
	private $delay_between_visits;

	#[Groups(['visit_type'])]
	#[ORM\ManyToOne(targetEntity: WorksiteStatus::class, inversedBy: 'visitTypes')]
	#[ORM\JoinColumn(nullable: true)]
	private $worksite_status;

	#[Groups(['visit_type'])]
	#[ORM\Column(type: 'boolean')]
	private $is_allowed_from_installation_only;

	#[Groups(['visit_type'])]
	#[ORM\Column(type: 'boolean')]
	private $has_fixed_planification;

	private ?int $worksite_id;

	#[Groups(['visit_type'])]
	#[ORM\Column(type: 'dateinterval')]
	private $relational_time;

	public function __construct()
	{
		$this->steps = new ArrayCollection();
		$this->worksites = new ArrayCollection();
		$this->visits = new ArrayCollection();
	}

	#[Groups('visit_type')]
	public function getId(): ?int
	{
		return $this->id;
	}

	#[Groups(['worksite', 'worksite_summary', 'visit_type'])]
	public function getCode(): ?string
	{
		return implode(" + ", $this->steps->map(fn($s) => $s->getCode())->toArray());
	}

	/**
	 * @return Collection|VisitStepType[]
	 */
	public function getSteps(): Collection
	{
		return $this->steps;
	}

	public function addStep(VisitStepType $step): self
	{
		if (!$this->steps->contains($step)) {
			$this->steps[] = $step;
		}

		return $this;
	}

	public function removeStep(VisitStepType $step): self
	{
		$this->steps->removeElement($step);

		return $this;
	}

	/**
	 * @return Collection|Worksite[]
	 */
	public function getWorksites(): Collection
	{
		return $this->worksites;
	}

	public function addWorksite(Worksite $worksite): self
	{
		if (!$this->worksites->contains($worksite)) {
			$this->worksites[] = $worksite;
			$worksite->setNextVisitType($this);
		}

		return $this;
	}

	public function removeWorksite(Worksite $worksite): self
	{
		if ($this->worksites->removeElement($worksite)) {
			// set the owning side to null (unless already changed)
			if ($worksite->getNextVisitType() === $this) {
				$worksite->setNextVisitType(null);
			}
		}

		return $this;
	}

	/**
	 * @return Collection|Visit[]
	 */
	public function getVisits(): Collection
	{
		return $this->visits;
	}

	public function addVisit(Visit $visit): self
	{
		if (!$this->visits->contains($visit)) {
			$this->visits[] = $visit;
			$visit->setType($this);
		}

		return $this;
	}

	public function removeVisit(Visit $visit): self
	{
		if ($this->visits->removeElement($visit)) {
			// set the owning side to null (unless already changed)
			if ($visit->getType() === $this) {
				$visit->setType(null);
			}
		}

		return $this;
	}

	public function getShortName(): ?string
	{
		return $this->short_name;
	}

	public function setShortName(string $short_name): self
	{
		$this->short_name = $short_name;

		return $this;
	}

	public function getLongName(): ?string
	{
		return $this->long_name;
	}

	public function setLongName(string $long_name): self
	{
		$this->long_name = $long_name;

		return $this;
	}

	public function getDelayBetweenVisits(): ?DateInterval
	{
		return $this->delay_between_visits;
	}

	public function setDelayBetweenVisits(?DateInterval $delay_between_visits): self
	{
		$this->delay_between_visits = $delay_between_visits;

		return $this;
	}

	public function getWorksiteStatus(): ?WorksiteStatus
	{
		return $this->worksite_status;
	}

	public function setWorksiteStatus(?WorksiteStatus $worksite_status): self
	{
		$this->worksite_status = $worksite_status;

		return $this;
	}

	public function getIsAllowedFromInstallationOnly(): ?bool
	{
		return $this->is_allowed_from_installation_only;
	}

	public function setIsAllowedFromInstallationOnly(bool $is_allowed_from_installation_only): self
	{
		$this->is_allowed_from_installation_only = $is_allowed_from_installation_only;

		return $this;
	}

	public function getHasFixedPlanification(): ?bool
	{
		return $this->has_fixed_planification;
	}

	public function setHasFixedPlanification(bool $has_fixed_planification): self
	{
		$this->has_fixed_planification = $has_fixed_planification;

		return $this;
	}

	/**
	 * @return int|null
	 */
	public function getWorksiteId(): ?int
	{
		return $this->worksite_id;
	}

	/**
	 * @param int|null $worksite_id
	 * @return VisitType
	 */
	public function setWorksiteId(?int $worksite_id): VisitType
	{
		$this->worksite_id = $worksite_id;
		return $this;
	}

	public function getRelationalTime(): ?DateInterval
	{
		return $this->relational_time;
	}

	public function setRelationalTime(DateInterval $relational_time): self
	{
		$this->relational_time = $relational_time;

		return $this;
	}
}

api/templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block stylesheets %}
        {% for path in encore_entry_css_files('app') %}
            <link rel="stylesheet" href="{{ pdf ? path|split('/')|last : absolute_url(path) }}">
        {% endfor %}
    {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
{% block body %}{% endblock %}
{% block javascripts %}
    {% for path in encore_entry_js_files('app') %}
        <script defer src="{{ pdf ? path|split('/')|last : absolute_url(path) }}"></script>
    {% endfor %}
{% endblock %}
</body>
</html>

<!DOCTYPE html>

api/templates/report_components.html.twig
{% macro worksite_info(value, margin=true) %}
    <div class="border-b border-dotted border-gray-700 {{ margin ? "mb-1" : "" }}">{{ value }}</div>
{% endmacro %}

{% macro report_section(title, elements) %}
    <ul class="list-disc ml-4 mb-4">
        <li>
            <span class="text-lg font-bold uppercase">{{ title }}</span>
            <ul class="mt-2">
                {% for element in elements %}
                    <li class="flex items-center gap-2 mb-1">
                        <input type="checkbox" id="{{ element.id ~ "_checkbox" }}" name="{{ element.id ~ "_checkbox" }}"
                               class="border border-black w-7 h-7" {{ (element.checked is defined and element.checked) or (element.value is defined and element.value != '')? 'checked' : '' }}>
                        <label for="{{ element.id ~ "_checkbox" }}" class="text-md">{{ element.label | raw }}</label>
                        {% if element.value is defined %}
                            <input type="text" id="{{ element.id }}" name="{{ element.id }}"
                                   class=" border-b border-dotted border-gray-700 max-w-full flex-grow"
                                   value="{{ element.value }}">
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </li>
    </ul>
{% endmacro %}

{% macro elimination_section(elements) %}
    <div class="flex flex-col mt-6 page-break">
        {% for element in elements %}
            <div class="flex items-center gap-2 mb-1">
                <input type="checkbox" id="{{ element.id ~ "_checkbox" }}" name="{{ element.id ~ "_checkbox" }}"
                       class="border border-black w-7 h-7">
                <label for="{{ element.id ~ "_checkbox" }}"
                       class="text-lg font-bold uppercase">{{ element.label }}</label>
            </div>
        {% endfor %}
    </div>
{% endmacro %}

{% macro observation_section(value) %}
    <div class="flex flex-col mt-4 border-2 border-black">
        <div class="bg-gray-300 uppercase font-bold text-lg text-center border-b-2 border-black">Observations diverses
        </div>
        <label class="mx-1">
            <textarea rows="20" class="w-full resize-none focus:outline-none">{{ value }}</textarea>
        </label>
    </div>
{% endmacro %}

api/templates/visit_report.html.twig
{% extends 'base.html.twig' %}

{% import "report_components.html.twig" as components %}
{% import "logo.html.twig" as logo %}


{% block title %}Compte rendu de visite{% endblock %}

{% block body %}
    <div class="flex w-full mb-4">
        <div class="w-3/4 border-2 border-black bg-gray-200">
            <div class="flex flex-col text-lg m-2">
                <div class="flex justify-center relative mb-1">
                    <div class="absolute top-0 left-0">{{ worksite.code }}</div>
                    <div class="text-xl font-bold">CHANTIER :</div>
                    <div></div>
                </div>
                {{ components.worksite_info(worksite.name) }}
                {{ components.worksite_info(worksite.address.street) }}
                {{ components.worksite_info(worksite.address.postalCode ~ " " ~ worksite.address.city) }}
                {{ components.worksite_info("maximeinformatique@free.fr", false) }} {# TODO: Replace with email address #}
            </div>
        </div>
        {{ logo.logo() }}
    </div>
    <div class="flex justify-center font-bold text-xl mb-4">
        COMPTE RENDU VISITE N°<span class="mx-1 border-b border-dotted border-gray-700 font-normal">1</span> DU <span
                class="mx-1 border-b border-dotted border-gray-700 font-normal">{{ visitDate }}</span>
    </div>
    <div class="text-center italic mb-4">
        <span class="underline">RAPPEL</span> : par arrêtés préfectoraux de 2001 et 2002, les départements de la Gironde
        et des Landes
        sont déclarés infestés par les termites dans leur intégralité.
        L’élimination d’une colonie de termites ne doit donc pas être considérée comme une disparition
        durable et définitive de la menace qu’ils représentent pour les bâtiments, y compris ceux dans
        lesquels une colonie a déjà été éradiquée.
    </div>

    {{ components.report_section("Vérification stations extérieures sentri sol", [
        {
            id: "all_stations",
            label: "Toutes les stations",
            checked: false
        },
        {
            id: "connected_stations",
            label: "Stations connectées uniquement et stations voisines aux stations connectées (visite complémentaire)",
            checked: false
        }
    ]) }}

    {{ components.report_section("Stations connectées :", [
        {
            id: "sb_connec",
            label: 'Station(s) lntérieure(s) <span class="font-bold">SENTRI BOX</span> n°',
            value: stationInfos.connectedSB
        },
        {
            id: "ssol_connec",
            label: 'Station(s) Extérieure(s) <span class="font-bold">SENTRI SOL</span> n°',
            value: stationInfos.connectedSSOL
        }
    ]) }}

    {{ components.report_section("Consommation de la formulation insecticide : ", [
        {
            id: "sb_conso",
            label: 'Station(s) lntérieure(s) <span class="font-bold">SENTRI BOX</span> n°',
            value: stationInfos.consummatingSB
        },
        {
            id: "ssol_conso",
            label: 'Station(s) Extérieure(s) <span class="font-bold">SENTRI SOL</span> n°',
            value: stationInfos.consummatingSSOL
        }
    ]) }}

    {{ components.report_section("Entretien du matériel en place à l'extérieur : ", [
        {
            id: "ssol_remplacement",
            label: 'Remplacement station(s) <span class="font-bold">SENTRI SOL</span> n°',
            value: stationInfos.replacedSSOL
        },
        {
            id: "ssol_couvercle",
            label: 'Changement couvercle <span class="font-bold">SENTRI SOL</span> n°',
            value: stationInfos.lidChangedSSOL
        },
        {
            id: "ssol_rechargement",
            label: 'Rechargement / Changement appât <span class="font-bold">SENTRI SOL</span> n°',
            value: stationInfos.rechargedSSOL
        },
        {
            id: "ssol_ajout",
            label: 'Ajout de .... station(s) <span class="font-bold">SENTRI SOL</span> n°',
            value: ""
        }
    ]) }}

    {{ components.report_section("Maintenance du matériel en place à l'intérieur : ", [
        {
            id: "sb_rechargement",
            label: 'Rechargement / Changement appât <span class="font-bold">SENTRI BOX</span> n°',
            value: stationInfos.rechargedSB
        },
        {
            id: "sb_ajout",
            label: 'Ajout de .... station(s) <span class="font-bold">SENTRI BOX</span> n°',
            value: ""
        },
        {
            id: "sb_suppression",
            label: 'Suppression de .... station(s) <span class="font-bold">SENTRI BOX</span> n°',
            value: stationInfos.removedSB
        }
    ]) }}

    {{ components.report_section("Stations inaccessibles : ", [
        {
            id: "sb_inaccessible",
            label: 'Inaccessibilité des stations <span class="font-bold">SENTRI BOX</span> n°',
            value: stationInfos.notAccessibleSB
        },
        {
            id: "ssol_inaccessible",
            label: 'Inaccessibilité des stations <span class="font-bold">SENTRI SOL</span> n°',
            value: stationInfos.notAccessibleSSOL
        }
    ]) }}

    {{ components.elimination_section([
        {
            id: "elimination_start",
            label: "Constat de début d'élimination d'une colonie de termites",
            checked: false
        },
        {
            id: "elimination_end",
            label: "Constat d'élimination d'une infestation",
            checked: false
        }
    ]) }}

    {{ components.observation_section(diverseObservations) }}

    <div class="flex flex-col gap-y-6 mt-4">
        <div class="italic underline">Prochaine visite :</div>
        <div class="flex flex-row justify-around">
            <div>L'Opérateur <span class="font-bold">SENTRI* TECH</span> : Olivier BAZIN</div>
            <div>Le Client : {{ worksite.name }}</div>
        </div>
        <div class="font-bold italic text-center text-sm">
            Copyright SOS Termites - 800, av. du Parc des Expositions - 33260 LA TESTE - Tél. 05 56 83 94 00 -
            www.sos-termites.com
        </div>
    </div>

{% endblock %}